### ISSUE TITLE
Error while loading the hotkeys

### ISSUE THREAD

**Issue by majsboll** [Hyrules/WinHue3#132]
I am having problem with hotkeys. I can add them, and they work perfectly, but as soon as i restart the program, there is an error trying to load them at startup.

Added debug-log as attachment
[winhue-debug-error.txt](https://github.com/Hyrules/WinHue3/files/1502960/winhue-debug-error.txt)

**Comment by Hyrules** [comment]
I will take a look at this asap.

**Comment by majsboll** [comment]
Great. Just let me know if I can help in any way troubleshooting this.

**Comment by Hyrules** [comment]
Can you send me your hotkey file ? I would like to see what you have set as hotkey. This will help me find the problem. The file is located in you appdata folder in the WinHue folder.

**Comment by majsboll** [comment]
Sure, attached... 
[WinHueHotkeys.zip](https://github.com/Hyrules/WinHue3/files/1523978/WinHueHotkeys.zip)

(had to zip since github dont allow .set)

this one gives the same error: "Error while loading the hotkeys."

**Comment by majsboll** [comment]
the hotkeys loads fine as long as I dont have anything defined in
      "properties": {      },

If I for example just have:

{
  "listHotKeys": [
    {
      "Modifier": 6,
      "Key": 36,
      "objecType": "WinHue3.Philips_Hue.HueObjects.LightObject.Light, WinHue3, Version=3.0.311.0, Culture=neutral, PublicKeyToken=null",
      "id": "11",
      "Name": "test",
      "Description": "test"
    }
  ]
}

It loads fine (but ofcourse is pretty useless)

**Comment by Hyrules** [comment]
I can see the error. I can replicate it. but i'm still trying to figure out why it happens. I have some hotkeys as well but they don't case a crash.

**Comment by Hyrules** [comment]
This version should fix this.

[WinHue 3 RC 4 - 3.0.847.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1524063/WinHue.3.RC.4.-.3.0.847.0.Setup.zip)

**Comment by majsboll** [comment]
Thanx for the update. It loads the hotkeys as it should and i can use them.
Unfortunally, this version wont let me do any new hotkeys, as soon as I choose a light it crashes. I could do them manually editing in WinHueHotkeys.set with notepad and it loads up fint, but as soon as i edit och create a new hotkey action it crashes. 

I have attached crashlog.

[crash_log.txt](https://github.com/Hyrules/WinHue3/files/1524262/crash_log.txt)

**Comment by Hyrules** [comment]
I see... I'll fix that. Be right back.

**Comment by Hyrules** [comment]
This should do it.

[WinHue 3 RC 4 - 3.0.897.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1524323/WinHue.3.RC.4.-.3.0.897.0.Setup.zip)

**Comment by majsboll** [comment]
Just tried it and it still crashes... Really appreciate you taking time to try and solve this...


[crash_log - 2.txt](https://github.com/Hyrules/WinHue3/files/1524330/crash_log.-.2.txt)

**Comment by Hyrules** [comment]
the error here is not useful. I need to know what you try to do when it crash. Here I can edit, create hotkeys without any crashes.

**Comment by majsboll** [comment]
I try to create hotkeys, just like before. As soon as I choose a light or a scene, it crashes. Loading hotkeys seems to work fine.

I have tried with a fresh install but still same error.

![crash](https://user-images.githubusercontent.com/33978706/33520602-aabbe002-d7be-11e7-9bc6-6d4cecb8b05f.PNG)

**Comment by Hyrules** [comment]
look like for some reason your version does not seems to be able to create the control for the xy value.
You should see this. Notice the xy control in the xy_inc property.

![image](https://user-images.githubusercontent.com/3161577/33520721-66b2c22a-d78e-11e7-875f-39b6adee2baf.png)

**Comment by majsboll** [comment]
Thats strange...

I can try on another computer tomorrow running windows 10 (Iam running win7 on this one) and see if the problem is present on that system aswell...

**Comment by Hyrules** [comment]
I'll still try to fix this because If you have this chances are other are. I'll post another version here in a few. You can test it when you can.

**Comment by Hyrules** [comment]
Here is another one.

[WinHue 3 RC 4 - 3.0.902.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1524380/WinHue.3.RC.4.-.3.0.902.0.Setup.zip)

**Comment by majsboll** [comment]
Okey, so it seems it still crashes on my main computer runnign windows 7. It crashes in the same way, so as soon as i choose a light, it crashes. I still dont see the dual lines for XY.

![win7_crash](https://user-images.githubusercontent.com/33978706/33527677-18b91020-d855-11e7-82b5-f0f2c463b8c8.PNG)

I just tried the same version on my windows 10 laptop, and there it works fine, with no crashes!

![win10_ok](https://user-images.githubusercontent.com/33978706/33527679-2b1b38ce-d855-11e7-9b09-3bf7b916ea6f.PNG)

Let me know if and how I can gather more information for you.

**Comment by Hyrules** [comment]
First thing would be to check the version of .net framework you are running on your windows 7 pc. WinHue requires .net framework 4.5.1.

https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed

**Comment by majsboll** [comment]
Im running .NET Framework 4.7
![framework](https://user-images.githubusercontent.com/33978706/33527846-cc4a474c-d857-11e7-834a-19b442742ea3.PNG)

**Comment by Hyrules** [comment]
Indeed that's 4.7. if you select a light in the main view do you see the control ? it should show there as well.

**Comment by majsboll** [comment]
You mean if I see the X Y in main? If so, yes i do..
![main_light_selected](https://user-images.githubusercontent.com/33978706/33528201-fbdb560e-d85c-11e7-82a5-5db8a433d5ff.PNG)

**Comment by Hyrules** [comment]
No in the property grid. If you expand state you should see XY_INC and XY in the controls that crashes the hotkey editor.

**Comment by majsboll** [comment]
Hmm, if I try to expand the state it crashes
![crash](https://user-images.githubusercontent.com/33978706/33528244-a1245552-d85d-11e7-88c8-4d1f5c223132.PNG)

**Comment by Hyrules** [comment]
I think I know hat happens. Try this one and let me know what happens.

[WinHue 3 RC 4 - 3.0.927.0 Setup.zip](https://github.com/Hyrules/WinHue3/files/1525021/WinHue.3.RC.4.-.3.0.927.0.Setup.zip)

**Comment by majsboll** [comment]
YES! This version fixes it. Hotkeys works, and I can ecpand states.

Great work!

**Comment by Hyrules** [comment]
Thanks. After re-reading the error log you sent me that I was thinking not useful I finally understood what it meant. There was an error converting a value from a string to a decimal which could happen when you are in different language locale. For example with the number 105,7 which in some language can be also 105.7. Here in canada we use the dot symbol as separator the american for example uses the coma. That translated in an error on your side.

**Comment by majsboll** [comment]
Ah I see. 

Well good work finding the error. I dont know how this works, but I guess you can close this ticket :)
